export const msg = {
    // 汎用
    "DAY": "日",
    "HOUR": "時間",
    "MINUTE": "分",
    "SECOND": "秒",
    "BEFORE": "前",
    "AFTER": "後",
    "REST_OF": "残り",
    "START": "開始",
    "END": "終了",
    "CANCEL": "キャンセル",
    "SUBMIT": "提出",
    "BACK": "戻る",
    "YES": "はい",
    "NO": "いいえ",
    "OK": "OK",
    "MANAGE": "管理",
    "LOADING": "読み込み中...",

    // サインイン・サインアップ
    "SIGN_IN_TITLE": "ログイン",
    "EMAIL_LABEL": "メールアドレス",
    "PASSWORD_LABEL": "パスワード",
    "SIGN_IN_BUTTON": "ログインする",
    "NO_ACCOUNT_TEXT": "アカウントをお持ちでないですか？",
    "GO_TO_SIGN_UP": "新規登録はこちら",
    "ERROR_SIGN_IN": "ログイン処理に失敗しました",

    "SIGN_UP_TITLE": "アカウント登録",
    "LAST_NAME_LABEL": "姓",
    "FIRST_NAME_LABEL": "名",
    "SIGN_UP_BUTTON": "登録する",
    "ALREADY_HAVE_ACCOUNT": "すでにアカウントをお持ちですか？",
    "GO_TO_SIGN_IN": "ログインはこちら",
    "ERROR_SIGN_UP": "アカウント登録に失敗しました",

    "VERIFICATION_TITLE": "メール認証",
    "VERIFICATION_CODE_LABEL": "認証コード",
    "VERIFY_BUTTON": "認証する",
    "ERROR_VERIFICATION": "認証に失敗しました",
    "ERROR_PASSWORD_INCORRECT": "パスワードが間違っています。もう一度お試しください。",
    "ERROR_USER_NOT_FOUND": "アカウントが見つかりません。メールアドレスをご確認ください。",
    "ERROR_TOO_MANY_REQUESTS": "リクエストが多すぎます。しばらく時間をおいてから再度お試しください。",
    "ERROR_EMAIL_EXISTS": "このメールアドレスは既に登録されています。",
    "ERROR_PASSWORD_TOO_SHORT": "パスワードの文字数が不足しています。",
    "ERROR_PASSWORD_PWNED": "このパスワードは過去に漏洩した記録があるため、安全のため使用できません。",
    "ERROR_INVALID_EMAIL": "無効なメールアドレスの形式です。",
    "ERROR_SIGN_IN_DEFAULT": "ログインに失敗しました。",
    "ERROR_SIGN_UP_DEFAULT": "アカウント登録に失敗しました。",
    "ERROR_DETAIL_PREFIX": "詳細エラー: ",
    "ERROR_INVALID_CODE": "認証コードが間違っているか、有効期限が切れています。",
    "ERROR_BOT_PROTECTION": "セキュリティ機能によりブロックされました。ブラウザのキャッシュをクリアするか、画面を更新してください。",
    "ERROR_INTERNAL": "システム内部でエラーが発生しました。開発者にお問い合わせください。",
    "ERROR_ENTER_PASSWORD": "パスワードを入力してください。", 
    "SIGN_OUT": "サインアウト",
    "ACCOUNT_SETTINGS": "アカウント",
    "MANAGE_ACCOUNT_INFO": "アカウント情報管理",
    "PROFILE": "プロフィール",
    "SECURITY": "セキュリティ",
    "PROFILE_DETAILS": "プロフィール詳細",
    "UPDATE_PROFILE": "プロフィールを更新",
    "PASSWORD": "パスワード",
    "CHANGE_PASSWORD": "パスワードを変更する",
    "ACTIVE_DEVICES": "アクティブなデバイス",
    "THIS_DEVICE": "このデバイス",
    "PRIMARY": "プライマリ",
    "ADD_EMAIL": "メールアドレスの追加",
    "UPDATE_PROFILE_TITLE": "プロフィールの更新",
    "UPLOAD": "アップロード",
    "DELETE_ACTION": "削除",
    "RECOMMENDED_SIZE": "推奨サイズ 1:1、最大 10MB",
    "UPDATE_PASSWORD_TITLE": "パスワードの更新",
    "NEW_PASSWORD_LABEL": "新しいパスワード",
    "CONFIRM_PASSWORD_LABEL": "パスワードの確認",
    "SIGN_OUT_OTHER_DEVICES": "他のデバイスからサインアウト",
    "SIGN_OUT_OTHER_DEVICES_DESC": "古いパスワードを使用している可能性のあるすべてのデバイスからサインアウトすることをお勧めします。",
    "ERROR_PASSWORD_MISMATCH": "パスワードが一致しません。",
    "UNKNOWN_DEVICE": "不明なデバイス",
    "TIME_SUFFIX": "に",
    "ERROR_UPDATE_FAILED": "更新に失敗しました",
    "CURRENT_PASSWORD_LABEL": "現在のパスワード",
    "ERROR_ENTER_CURRENT_PASSWORD": "現在のパスワードを入力してください。",
    "REVERIFICATION_REQUIRED": "セキュリティのため、再認証が必要です。",
    "REVERIFICATION_DESC": "登録されているメールアドレスに送信された6桁の認証コードを入力して、変更を確定してください。",
    "SEND_CODE_AGAIN": "コードを再送信",

    // クラス参加ページ
    // /join/JoinClient.tsx
    "JOINED": "に参加しました。",
    "JOIN_ERROR": "クラスへの参加に失敗しました。",
    "EXIST": " が存在します。",
    "NOT_EXIST": "このクラスコードは存在しません。",
    "JOIN_CLASS": "クラスに参加",
    "ENTER_CODE": "参加するクラスのコードを入力してください。",
    "CLASSCODE": "クラスコード",
    "JOIN": "参加",

    // マイページ 一部上より流用有
    // /mypage/student/page.tsx
    // /mypage/teacher/page.tsx
    "NO_TEST": "テストはありません",
    "CLASS": "クラス",
    "TEST": "テスト",
    "CLASS_NAME": "クラス名",
    "CREATE_CLASS": "クラスを作成",
    "CREATE_TEST": "テストを作成",
    "TESTS_IN_CLASS": "テスト一覧",
    "CLASS_CREATED": "クラスを作成しました",
    "ERROR_NO_CLASS_NAME": "クラス名を入力してください。",
    "ERROR_NO_TEACHER": "最低一人の教師を追加してください。",
    "SEARCH_STUDENT": "学生検索",
    "SEARCH_TEACHER": "教師検索",
    "DELETE_USER": "削除",

    // マイページ用テストカード
    // /compornents/StudentTestCard.tsx
    "SUBMITTED": "提出済",
    "NOT_SUBMITTED": "未提出",

    // /compornents/TestCards.tsx
    "SOLVE": "解答",
    "GRADING": "採点",
    "EDIT": "編集",

    // テスト作成ページ
    // /teacher/createTest/page.tsx
    "CREATE_NEW_TEST": "テスト作成",
    "EDIT_TEST": "テストの編集",
    "PUBLISH_TEST": "テストを公開",
    "PUBLISHED": "公開中",
    "UNPUBLISHED": "非公開",
    "SAVE": "保存",
    "SUCCESS_CREATE_TEST": "テストの作成が完了しました",
    "SUCCESS_SAVE_TEST": "テストを保存しました",
    "OPEN_JSON": "テストを開く",
    "SAVE_JSON": "テストを保存",
    "ERROR_TEST_NOT_FOUND": "指定されたテストが見つからないか、アクセス権限がありません。",
    "ERROR_FILE_LOAD": "ファイルの読み込みに失敗しました。形式を確認してください。",

    // バリデーション・エラー
    "ERROR_START_AFTER_END": "開始日が締め切りより後です",
    "ERROR_NO_CLASS": "クラスが選択されていません",
    "ERROR_CONTENT_MISSING": "コンテンツが挿入されていません",
    "WARNING_START_DATE_PAST": "開始日が現在日より前です",

    // メタデータタブ
    "METADATA": "基本設定",
    "BASIC_INFO": "基本情報",
    "TEST_TITLE": "テストタイトル",
    "TEST_SUMMARY": "説明 / 概要",
    "SCHEDULE": "スケジュール",
    "START_DATE": "開始日",
    "END_DATE": "終了日",
    "ASSIGNMENT": "割り当て",
    "TARGET_CLASS": "対象クラス",

    // セクションタブ
    "SECTION_NUMBER": "大問",
    "ADD_SECTION": "セクション追加",
    "SECTION_SETTINGS": "設定",
    "DELETE_SECTION": "セクションを削除",
    "SECTION_SUMMARY_LABEL": "セクション概要",
    "PREVIEW": "プレビュー",
    "QUESTIONS_LIST": "問題一覧",
    "ADD_QUESTION": "問題を追加",
    "ADD_ANOTHER_QUESTION": "次の問題を追加",
    "NO_QUESTIONS_ALERT": "問題がまだ追加されていません。「問題を追加」をクリックして開始してください。",

    // 問題カード
    "QUESTION_NUMBER_PREFIX": "問",
    "QUESTION_TEXT_LABEL": "問題文 ",
    "QUESTION_PREVIEW": "問題プレビュー",
    "MEDIA_ATTACHMENT": "メディア添付",
    "ATTACHMENT_TYPE": "添付タイプ",
    "NO_ATTACHMENT": "添付なし",
    "UPLOAD_FILE": "アップロード",
    "FILE_UPLOADED": "ファイルアップロード済",
    "ATTACHMENT_PREVIEW": "添付プレビュー",
    "ANSWER_KEY": "解答設定",
    "ANSWER_FORMULA_LABEL": "正答 (LaTeX)",
    "ANSWER_PLACEHOLDER": "例: x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}",

    "CONFIRM_DELETE_SUBMISSIONS_TITLE": "提出データの削除確認",
    "CONFIRM_DELETE_SUBMISSIONS_MESSAGE": "このテストには既に提出データが存在します。保存すると既存の提出データと採点結果はすべて削除されますが、よろしいですか？",
    "PROCEED_SAVE": "削除して保存",

    // 結果ページ
    // /test/[id]/result/page.tsx (等)
    "CANT_OPEN_PAGE": "ページを開けません",
    "FORM_ID": "フォームID:",
    "NOT_GRADED": "未採点",
    "POINT_DISPLAY": "点数: {n} 点",
    "TRUE_ANS": "正答",
    "PREV_PART": "前のパート",
    "NEXT_PART": "次のパート",
    "SCORE": "点数",
    "POINTS": "点",

    // 解答ページ
    // /test/[id]/page.tsx
    "NO_TEST_FOUND": "テストが見つかりません",
    "SUBMISSION_COMPLETED": "提出完了",
    "CHECK_RESULTS": "結果を確認する ＞",
    "ERROR": "エラー",
    "SENT": "提出しました！",
    "SEND_FAILED": "提出に失敗しました",
    "SEND": "提出",
    "SENDING": "送信中...",

    //  /teacher/grading/[testid]/page.tsx
    "PART": "Part",
    "NO_TEST_DATA": "テストデータが見つかりません。",
    "TOTAL_POINT": "合計点",
    "UNGRADED_COUNT": "未採点",
    "SUCCESS_SAVE_GRADING": "採点データを保存しました。",
    "ERROR_OCCURRED": "エラーが発生しました。",
    "EXPORT_CSV": "CSVエクスポート",
    "CLASS_ID": "クラスID",
    "TEST_ID": "テストID",
    "CSV_PART_QNUMBER": "Part-QNumber",
    "CSV_QUESTION": "Question",
    "CSV_ANSWER": "Answer",

    // class
    "EDIT_CLASS": "クラスを編集",
    "UPDATE_CLASS": "クラスを更新する",
    "SUCCESS_UPDATE": "クラスを更新しました",
    "ADDED_STUDENTS": "追加済みの学生",
    "ADDED_TEACHERS": "追加済みの教師",
    "CLASS_INFO": "クラス基本情報",
    "STUDENT_SECTION": "学生",
    "TEACHER_SECTION": "教師",
    "SEARCH_PLACEHOLDER_STUDENT": "名前やメールアドレスで学生を検索",
    "SEARCH_PLACEHOLDER_TEACHER": "名前やメールアドレスで教師を検索",
    "CURRENT_MEMBERS": "現在のメンバー",
    "NO_MEMBERS": "メンバーが追加されていません",
    "UPLOAD_ICON": "アイコン画像を選択",
    "DELETE_ICON": "アイコンを削除",
    "COPIED": "クリップボードにコピーしました",
    "INVITATION_QR": "招待用QRコード",
    "INVITATION_URL": "招待用URL",
    "COPY_URL": "URLをコピー",
    //ClassDetail
    "CLASS_DETAILS": "クラス詳細",
    "TEST_LIST": "テスト一覧",
    "MEMBERS": "メンバー",
    "SUBMISSION_STATUS": "提出状況",
    "NO_TESTS_IN_CLASS": "このクラスにはまだテストがありません",
    "VIEW_DETAILS": "詳細",
    "SUBMITTED_STUDENTS": "提出済みの学生",
    "UNSUBMITTED_STUDENTS": "未提出の学生",
    "ERROR_INVALID_URL": "無効なURLです",
    "GRADE": "採点",
    "TAKE_TEST": "解答する",
    "VIEW_RESULT": "結果を見る",
    "BEFORE_SUBMISSION_PERIOD": "提出期間前です",
    "SUBMISSION_TIME": "提出時間",
    "DEADLINE": "期限より",
    "LATE_SUBMISSION": "遅れて提出しました",
    "EARLY_SUBMISSION": "早く提出しました",
    "MAX_RESUBMISSIONS": "再提出回数の上限",
    "REMAINING_RESUBMISSIONS": "残り再提出回数",
    "RESUBMIT": "再度提出する",
    "RESUBMIT_W": "再提出",

    "CREATE_FOLDER": "フォルダを作成",
    "NEW_FOLDER_NAME": "フォルダ名",
    "DELETE_FOLDER_CONFIRM": "フォルダを削除しますか？（中身のアイテムは外に移動されます）",
    "DROP_HERE": "（ここへドロップして追加）",
    "RENAME_FOLDER": "名前の変更",
    "DELETE_FOLDER": "削除",
    "CHANGE_FOLDER_COLOR": "色の変更",
    "SELECT_COLOR": "色を選択",
    "ALLOCATION_POINT": "配点",
}
