"use client";
import { useContext } from "react";
import { LangContext } from "@/compornents/LangProvider";

export const jaDict = {
    "APP_NAME": "NuMASCH",
    // 汎用
    "DAY": "日",
    "HOUR": "時間",
    "MINUTE": "分",
    "SECOND": "秒",
    "BEFORE": "前",
    "AFTER": "後",
    "REST_OF": "残り",
    "START": "開始",
    "END": "終了",
    "CANCEL": "キャンセル",
    "SUBMIT": "提出",
    "BACK": "戻る",
    "YES": "はい",
    "NO": "いいえ",
    "OK": "OK",
    "MANAGE": "管理",
    "LOADING": "読み込み中...",

    // サインイン・サインアップ
    "SIGN_IN_TITLE": "ログイン",
    "EMAIL_LABEL": "メールアドレス",
    "PASSWORD_LABEL": "パスワード",
    "SIGN_IN_BUTTON": "ログインする",
    "NO_ACCOUNT_TEXT": "アカウントをお持ちでないですか？",
    "GO_TO_SIGN_UP": "新規登録はこちら",
    "ERROR_SIGN_IN": "ログイン処理に失敗しました",

    "SIGN_UP_TITLE": "アカウント登録",
    "LAST_NAME_LABEL": "姓",
    "FIRST_NAME_LABEL": "名",
    "SIGN_UP_BUTTON": "登録する",
    "ALREADY_HAVE_ACCOUNT": "すでにアカウントをお持ちですか？",
    "GO_TO_SIGN_IN": "ログインはこちら",
    "ERROR_SIGN_UP": "アカウント登録に失敗しました",

    "VERIFICATION_TITLE": "メール認証",
    "VERIFICATION_CODE_LABEL": "認証コード",
    "VERIFY_BUTTON": "認証する",
    "ERROR_VERIFICATION": "認証に失敗しました",
    "ERROR_PASSWORD_INCORRECT": "パスワードが間違っています。もう一度お試しください。",
    "ERROR_USER_NOT_FOUND": "アカウントが見つかりません。メールアドレスをご確認ください。",
    "ERROR_TOO_MANY_REQUESTS": "リクエストが多すぎます。しばらく時間をおいてから再度お試しください。",
    "ERROR_EMAIL_EXISTS": "このメールアドレスは既に登録されています。",
    "ERROR_PASSWORD_TOO_SHORT": "パスワードの文字数が不足しています。",
    "ERROR_PASSWORD_PWNED": "このパスワードは過去に漏洩した記録があるため、安全のため使用できません。",
    "ERROR_INVALID_EMAIL": "無効なメールアドレスの形式です。",
    "ERROR_SIGN_IN_DEFAULT": "ログインに失敗しました。",
    "ERROR_SIGN_UP_DEFAULT": "アカウント登録に失敗しました。",
    "ERROR_DETAIL_PREFIX": "詳細エラー: ",
    "ERROR_INVALID_CODE": "認証コードが間違っているか、有効期限が切れています。",
    "ERROR_BOT_PROTECTION": "セキュリティ機能によりブロックされました。ブラウザのキャッシュをクリアするか、画面を更新してください。",
    "ERROR_INTERNAL": "システム内部でエラーが発生しました。開発者にお問い合わせください。",
    "ERROR_ENTER_PASSWORD": "パスワードを入力してください。",
    "SIGN_OUT": "サインアウト",
    "ACCOUNT_SETTINGS": "アカウント",
    "MANAGE_ACCOUNT_INFO": "アカウント情報管理",
    "PROFILE": "プロフィール",
    "SECURITY": "セキュリティ",
    "APPEARANCE": "外観", 
    "THEME": "テーマ",
    "THEME_LIGHT": "ライトモード", 
    "THEME_DARK": "ダークモード",
    "PROFILE_DETAILS": "プロフィール詳細",
    "UPDATE_PROFILE": "プロフィールを更新",
    "PASSWORD": "パスワード",
    "CHANGE_PASSWORD": "パスワードを変更する",
    "ACTIVE_DEVICES": "アクティブなデバイス",
    "THIS_DEVICE": "このデバイス",
    "PRIMARY": "プライマリ",
    "ADD_EMAIL": "メールアドレスの追加",
    "UPDATE_PROFILE_TITLE": "プロフィールの更新",
    "UPLOAD": "アップロード",
    "DELETE_ACTION": "削除",
    "RECOMMENDED_SIZE": "推奨サイズ 1:1、最大 10MB",
    "UPDATE_PASSWORD_TITLE": "パスワードの更新",
    "NEW_PASSWORD_LABEL": "新しいパスワード",
    "CONFIRM_PASSWORD_LABEL": "パスワードの確認",
    "SIGN_OUT_OTHER_DEVICES": "他のデバイスからサインアウト",
    "SIGN_OUT_OTHER_DEVICES_DESC": "古いパスワードを使用している可能性のあるすべてのデバイスからサインアウトすることをお勧めします。",
    "ERROR_PASSWORD_MISMATCH": "パスワードが一致しません。",
    "UNKNOWN_DEVICE": "不明なデバイス",
    "TIME_SUFFIX": "に",
    "ERROR_UPDATE_FAILED": "更新に失敗しました",
    "CURRENT_PASSWORD_LABEL": "現在のパスワード",
    "ERROR_ENTER_CURRENT_PASSWORD": "現在のパスワードを入力してください。",
    "REVERIFICATION_REQUIRED": "セキュリティのため、再認証が必要です。",
    "REVERIFICATION_DESC": "登録されているメールアドレスに送信された6桁の認証コードを入力して、変更を確定してください。",
    "SEND_CODE_AGAIN": "コードを再送信",

    // クラス参加ページ
    // /join/JoinClient.tsx
    "JOINED": "に参加しました。",
    "JOIN_ERROR": "クラスへの参加に失敗しました。",
    "EXIST": " が存在します。",
    "NOT_EXIST": "このクラスコードは存在しません。",
    "JOIN_CLASS": "クラスに参加",
    "ENTER_CODE": "参加するクラスのコードを入力してください。",
    "CLASSCODE": "クラスコード",
    "JOIN": "参加",

    // マイページ 一部上より流用有
    // /mypage/student/page.tsx
    // /mypage/teacher/page.tsx
    "NO_TEST": "テストはありません",
    "CLASS": "クラス",
    "TEST": "テスト",
    "CLASS_NAME": "クラス名",
    "CREATE_CLASS": "クラスを作成",
    "CREATE_TEST": "テストを作成",
    "TESTS_IN_CLASS": "テスト一覧",
    "CLASS_CREATED": "クラスを作成しました",
    "ERROR_NO_CLASS_NAME": "クラス名を入力してください。",
    "ERROR_NO_TEACHER": "最低一人の教師を追加してください。",
    "SEARCH_STUDENT": "学生検索",
    "SEARCH_TEACHER": "教師検索",
    "DELETE_USER": "削除",

    // マイページ用テストカード
    // /compornents/StudentTestCard.tsx
    "SUBMITTED": "提出済",
    "NOT_SUBMITTED": "未提出",

    // /compornents/TestCards.tsx
    "SOLVE": "解答",
    "GRADING": "採点",
    "EDIT": "編集",

    // テスト作成ページ
    // /teacher/createTest/page.tsx
    "CREATE_NEW_TEST": "テスト作成",
    "EDIT_TEST": "テストの編集",
    "PUBLISH_TEST": "テストを公開",
    "PUBLISHED": "公開中",
    "UNPUBLISHED": "非公開",
    "SAVE": "保存",
    "SUCCESS_CREATE_TEST": "テストの作成が完了しました",
    "SUCCESS_SAVE_TEST": "テストを保存しました",
    "OPEN_JSON": "テストを開く",
    "SAVE_JSON": "テストを保存",
    "ERROR_TEST_NOT_FOUND": "指定されたテストが見つからないか、アクセス権限がありません。",
    "ERROR_FILE_LOAD": "ファイルの読み込みに失敗しました。形式を確認してください。",

    // バリデーション・エラー
    "ERROR_START_AFTER_END": "開始日が締め切りより後です",
    "ERROR_NO_CLASS": "クラスが選択されていません",
    "ERROR_CONTENT_MISSING": "コンテンツが挿入されていません",
    "WARNING_START_DATE_PAST": "開始日が現在日より前です",

    // メタデータタブ
    "METADATA": "基本設定",
    "BASIC_INFO": "基本情報",
    "TEST_TITLE": "テストタイトル",
    "TEST_SUMMARY": "説明 / 概要",
    "SCHEDULE": "スケジュール",
    "START_DATE": "開始日",
    "END_DATE": "終了日",
    "ASSIGNMENT": "割り当て",
    "TARGET_CLASS": "対象クラス",

    // 大問タブ
    "SECTION_NUMBER": "大問",
    "ADD_SECTION": "大問追加",
    "SECTION_SETTINGS": "設定",
    "DELETE_SECTION": "大問を削除",
    "SECTION_SUMMARY_LABEL": "大問概要",
    "PREVIEW": "プレビュー",
    "QUESTIONS_LIST": "問題一覧",
    "ADD_QUESTION": "問題を追加",
    "ADD_ANOTHER_QUESTION": "次の問題を追加",
    "NO_QUESTIONS_ALERT": "問題がまだ追加されていません。「問題を追加」をクリックして開始してください。",

    // 問題カード
    "QUESTION_NUMBER_PREFIX": "問",
    "QUESTION_TEXT_LABEL": "問題文 ",
    "QUESTION_PREVIEW": "問題プレビュー",
    "MEDIA_ATTACHMENT": "メディア添付",
    "ATTACHMENT_TYPE": "添付タイプ",
    "NO_ATTACHMENT": "添付なし",
    "UPLOAD_FILE": "アップロード",
    "FILE_UPLOADED": "ファイルアップロード済",
    "ATTACHMENT_PREVIEW": "添付プレビュー",
    "ENTER_ANSWER":"解答を入力",
    "ANSWER_KEY": "解答設定",
    "ANSWER_FORMULA_LABEL": "正答 (LaTeX)",
    "ANSWER_PLACEHOLDER": "例: x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}",

    "CONFIRM_DELETE_SUBMISSIONS_TITLE": "提出データの削除確認",
    "CONFIRM_DELETE_SUBMISSIONS_MESSAGE": "このテストには既に提出データが存在します。保存すると既存の提出データと採点結果はすべて削除されますが、よろしいですか？",
    "PROCEED_SAVE": "削除して保存",

    // 結果ページ
    // /test/[id]/result/page.tsx (等)
    "CANT_OPEN_PAGE": "ページを開けません",
    "FORM_ID": "フォームID:",
    "NOT_GRADED": "未採点",
    "POINT_DISPLAY": "点数: {n} 点",
    "TRUE_ANS": "正答",
    "PREV_PART": "前のパート",
    "NEXT_PART": "次のパート",
    "SCORE": "点数",
    "POINTS": "点",

    // 解答ページ
    // /test/[id]/page.tsx
    "NO_TEST_FOUND": "テストが見つかりません",
    "SUBMISSION_COMPLETED": "提出完了",
    "CHECK_RESULTS": "結果を確認する ＞",
    "ERROR": "エラー",
    "SENT": "提出しました！",
    "SEND_FAILED": "提出に失敗しました",
    "SEND": "提出",
    "SENDING": "送信中...",

    //  /teacher/grading/[testid]/page.tsx
    "PART": "Part",
    "NO_TEST_DATA": "テストデータが見つかりません。",
    "TOTAL_POINT": "合計点",
    "UNGRADED_COUNT": "未採点",
    "SUCCESS_SAVE_GRADING": "採点データを保存しました。",
    "ERROR_OCCURRED": "エラーが発生しました。",
    "EXPORT_CSV": "CSVエクスポート",
    "CLASS_ID": "クラスID",
    "TEST_ID": "テストID",
    "CSV_PART_QNUMBER": "Part-QNumber",
    "CSV_QUESTION": "Question",
    "CSV_ANSWER": "Answer",

    // class
    "EDIT_CLASS": "クラスを編集",
    "UPDATE_CLASS": "クラスを更新する",
    "SUCCESS_UPDATE": "クラスを更新しました",
    "ADDED_STUDENTS": "追加済みの学生",
    "ADDED_TEACHERS": "追加済みの教師",
    "CLASS_INFO": "クラス基本情報",
    "STUDENT_SECTION": "学生",
    "TEACHER_SECTION": "教師",
    "SEARCH_PLACEHOLDER_STUDENT": "名前やメールアドレスで学生を検索",
    "SEARCH_PLACEHOLDER_TEACHER": "名前やメールアドレスで教師を検索",
    "CURRENT_MEMBERS": "現在のメンバー",
    "NO_MEMBERS": "メンバーが追加されていません",
    "UPLOAD_ICON": "アイコン画像を選択",
    "DELETE_ICON": "アイコンを削除",
    "COPIED": "クリップボードにコピーしました",
    "INVITATION_QR": "招待用QRコード",
    "INVITATION_URL": "招待用URL",
    "COPY_URL": "URLをコピー",
    //ClassDetail
    "CLASS_DETAILS": "クラス詳細",
    "TEST_LIST": "テスト一覧",
    "MEMBERS": "メンバー",
    "SUBMISSION_STATUS": "提出状況",
    "NO_TESTS_IN_CLASS": "このクラスにはまだテストがありません",
    "VIEW_DETAILS": "詳細",
    "SUBMITTED_STUDENTS": "提出済みの学生",
    "UNSUBMITTED_STUDENTS": "未提出の学生",
    "ERROR_INVALID_URL": "無効なURLです",
    "GRADE": "採点",
    "TAKE_TEST": "解答する",
    "VIEW_RESULT": "結果を見る",
    "BEFORE_SUBMISSION_PERIOD": "提出期間前です",
    "SUBMISSION_TIME": "提出時間",
    "DEADLINE": "期限より",
    "LATE_SUBMISSION": "遅れて提出しました",
    "EARLY_SUBMISSION": "早く提出しました",
    "MAX_RESUBMISSIONS": "再提出回数の上限",
    "REMAINING_RESUBMISSIONS": "残り再提出回数",
    "RESUBMIT": "再度提出する",
    "RESUBMIT_W": "再提出",

    "CREATE_FOLDER": "フォルダを作成",
    "NEW_FOLDER_NAME": "フォルダ名",
    "DELETE_FOLDER_CONFIRM": "フォルダを削除しますか？（中身のアイテムは外に移動されます）",
    "DROP_HERE": "（ここへドロップして追加）",
    "RENAME_FOLDER": "名前の変更",
    "DELETE_FOLDER": "削除",
    "CHANGE_FOLDER_COLOR": "色の変更",
    "SELECT_COLOR": "色を選択",
    "ALLOCATION_POINT": "配点",
    "NAME": "名前",
    "OVERDUE": "期限遅れ",
    "ON_TIME": "期限内",
    "SUBMIT_PREFIX": "提出: ",
    "LATE_PREFIX": "期限から ",
    "LATE_SUFFIX": "遅れ",
    "LESS_THAN_A_MINUTE": "1分未満",
    "RAW_TEX": "原文TeX",
    "CLOSE": "閉じる",
    "ANSWER_LABEL": "解答",
    "SCORE_LABEL": "得点",
    "MOVE_UP": "上へ",
    "MOVE_DOWN": "下へ",
    "DUPLICATE": "コピーを作成",
    "AUTO_GRADING": "自動採点",
    "AUTO_GRADING_CONFIRM_TITLE": "自動採点の実行",
    "AUTO_GRADING_CONFIRM_MESSAGE": "自動採点を実行すると、現在入力されている点数が上書きされます。よろしいですか？",
    "EXECUTE": "実行",
    "FORMATED_TEX": "フォーマットされたTeX",
    "ITEMS": "アイテム",
    "SHOW_QUESTION": "問題を表示",
};

export const enDict = {
    "APP_NAME": "NuMASCH",
    // 汎用
    "DAY": "Day",
    "HOUR": "Hour",
    "MINUTE": "Minute",
    "SECOND": "Second",
    "BEFORE": "Before",
    "AFTER": "After",
    "REST_OF": "Remaining",
    "START": "Start",
    "END": "End",
    "CANCEL": "Cancel",
    "SUBMIT": "Submit",
    "BACK": "Back",
    "YES": "Yes",
    "NO": "No",
    "OK": "OK",
    "MANAGE": "Manage",
    "LOADING": "Loading...",

    // サインイン・サインアップ
    "SIGN_IN_TITLE": "Sign In",
    "EMAIL_LABEL": "Email Address",
    "PASSWORD_LABEL": "Password",
    "SIGN_IN_BUTTON": "Sign In",
    "NO_ACCOUNT_TEXT": "Don't have an account?",
    "GO_TO_SIGN_UP": "Sign up here",
    "ERROR_SIGN_IN": "Sign in failed",

    "SIGN_UP_TITLE": "Sign Up",
    "LAST_NAME_LABEL": "Last Name",
    "FIRST_NAME_LABEL": "First Name",
    "SIGN_UP_BUTTON": "Sign Up",
    "ALREADY_HAVE_ACCOUNT": "Already have an account?",
    "GO_TO_SIGN_IN": "Sign in here",
    "ERROR_SIGN_UP": "Sign up failed",

    "VERIFICATION_TITLE": "Email Verification",
    "VERIFICATION_CODE_LABEL": "Verification Code",
    "VERIFY_BUTTON": "Verify",
    "ERROR_VERIFICATION": "Verification failed",
    "ERROR_PASSWORD_INCORRECT": "Incorrect password. Please try again.",
    "ERROR_USER_NOT_FOUND": "Account not found. Please check your email address.",
    "ERROR_TOO_MANY_REQUESTS": "Too many requests. Please try again later.",
    "ERROR_EMAIL_EXISTS": "This email address is already registered.",
    "ERROR_PASSWORD_TOO_SHORT": "Password is too short.",
    "ERROR_PASSWORD_PWNED": "This password has been exposed in a data breach and cannot be used for security reasons.",
    "ERROR_INVALID_EMAIL": "Invalid email format.",
    "ERROR_SIGN_IN_DEFAULT": "Sign in failed.",
    "ERROR_SIGN_UP_DEFAULT": "Sign up failed.",
    "ERROR_DETAIL_PREFIX": "Error Details: ",
    "ERROR_INVALID_CODE": "The verification code is incorrect or has expired.",
    "ERROR_BOT_PROTECTION": "Blocked by security features. Please clear your browser cache or refresh the page.",
    "ERROR_INTERNAL": "An internal system error occurred. Please contact the developer.",
    "ERROR_ENTER_PASSWORD": "Please enter your password.",
    "SIGN_OUT": "Sign Out",
    "ACCOUNT_SETTINGS": "Account",
    "MANAGE_ACCOUNT_INFO": "Manage Account Information",
    "PROFILE": "Profile",
    "SECURITY": "Security",
    "APPEARANCE": "Appearance", 
    "THEME": "Theme",
    "THEME_LIGHT": "Light Mode", 
    "THEME_DARK": "Dark Mode",
    "PROFILE_DETAILS": "Profile Details",
    "UPDATE_PROFILE": "Update Profile",
    "PASSWORD": "Password",
    "CHANGE_PASSWORD": "Change Password",
    "ACTIVE_DEVICES": "Active Devices",
    "THIS_DEVICE": "This Device",
    "PRIMARY": "Primary",
    "ADD_EMAIL": "Add Email Address",
    "UPDATE_PROFILE_TITLE": "Update Profile",
    "UPLOAD": "Upload",
    "DELETE_ACTION": "Delete",
    "RECOMMENDED_SIZE": "Recommended size 1:1, Max 10MB",
    "UPDATE_PASSWORD_TITLE": "Update Password",
    "NEW_PASSWORD_LABEL": "New Password",
    "CONFIRM_PASSWORD_LABEL": "Confirm Password",
    "SIGN_OUT_OTHER_DEVICES": "Sign out from other devices",
    "SIGN_OUT_OTHER_DEVICES_DESC": "We recommend signing out of all devices that might be using an old password.",
    "ERROR_PASSWORD_MISMATCH": "Passwords do not match.",
    "UNKNOWN_DEVICE": "Unknown Device",
    "TIME_SUFFIX": "at",
    "ERROR_UPDATE_FAILED": "Update failed",
    "CURRENT_PASSWORD_LABEL": "Current Password",
    "ERROR_ENTER_CURRENT_PASSWORD": "Please enter your current password.",
    "REVERIFICATION_REQUIRED": "Re-verification is required for security reasons.",
    "REVERIFICATION_DESC": "Please enter the 6-digit verification code sent to your registered email address to confirm changes.",
    "SEND_CODE_AGAIN": "Resend Code",

    // クラス参加ページ
    // /join/JoinClient.tsx
    "JOINED": " joined.",
    "JOIN_ERROR": "Failed to join the class.",
    "EXIST": " exists.",
    "NOT_EXIST": "This class code does not exist.",
    "JOIN_CLASS": "Join Class",
    "ENTER_CODE": "Please enter the code of the class you want to join.",
    "CLASSCODE": "Class Code",
    "JOIN": "Join",

    // マイページ 一部上より流用有
    // /mypage/student/page.tsx
    // /mypage/teacher/page.tsx
    "NO_TEST": "No tests available",
    "CLASS": "Class",
    "TEST": "Test",
    "CLASS_NAME": "Class Name",
    "CREATE_CLASS": "Create Class",
    "CREATE_TEST": "Create Test",
    "TESTS_IN_CLASS": "Test List",
    "CLASS_CREATED": "Class created successfully",
    "ERROR_NO_CLASS_NAME": "Please enter a class name.",
    "ERROR_NO_TEACHER": "Please add at least one teacher.",
    "SEARCH_STUDENT": "Search Student",
    "SEARCH_TEACHER": "Search Teacher",
    "DELETE_USER": "Delete",

    // マイページ用テストカード
    // /compornents/StudentTestCard.tsx
    "SUBMITTED": "Submitted",
    "NOT_SUBMITTED": "Not Submitted",

    // /compornents/TestCards.tsx
    "SOLVE": "Take Test",
    "GRADING": "Grading",
    "EDIT": "Edit",

    // テスト作成ページ
    // /teacher/createTest/page.tsx
    "CREATE_NEW_TEST": "Create New Test",
    "EDIT_TEST": "Edit Test",
    "PUBLISH_TEST": "Publish Test",
    "PUBLISHED": "Published",
    "UNPUBLISHED": "Unpublished",
    "SAVE": "Save",
    "SUCCESS_CREATE_TEST": "Test created successfully",
    "SUCCESS_SAVE_TEST": "Test saved successfully",
    "OPEN_JSON": "Open Test",
    "SAVE_JSON": "Save Test",
    "ERROR_TEST_NOT_FOUND": "The specified test was not found or you do not have access permission.",
    "ERROR_FILE_LOAD": "Failed to load the file. Please check the format.",

    // バリデーション・エラー
    "ERROR_START_AFTER_END": "Start date is after the deadline",
    "ERROR_NO_CLASS": "No class selected",
    "ERROR_CONTENT_MISSING": "No content inserted",
    "WARNING_START_DATE_PAST": "Start date is in the past",

    // メタデータタブ
    "METADATA": "Basic Settings",
    "BASIC_INFO": "Basic Information",
    "TEST_TITLE": "Test Title",
    "TEST_SUMMARY": "Description / Summary",
    "SCHEDULE": "Schedule",
    "START_DATE": "Start Date",
    "END_DATE": "End Date",
    "ASSIGNMENT": "Assignment",
    "TARGET_CLASS": "Target Class",

    // 大問タブ
    "SECTION_NUMBER": "Section",
    "ADD_SECTION": "Add Section",
    "SECTION_SETTINGS": "Settings",
    "DELETE_SECTION": "Delete Section",
    "SECTION_SUMMARY_LABEL": "Section Summary",
    "PREVIEW": "Preview",
    "QUESTIONS_LIST": "Question List",
    "ADD_QUESTION": "Add Question",
    "ADD_ANOTHER_QUESTION": "Add Another Question",
    "NO_QUESTIONS_ALERT": "No questions have been added yet. Click 'Add Question' to start.",

    // 問題カード
    "QUESTION_NUMBER_PREFIX": "Q",
    "QUESTION_TEXT_LABEL": "Question Text ",
    "QUESTION_PREVIEW": "Question Preview",
    "MEDIA_ATTACHMENT": "Media Attachment",
    "ATTACHMENT_TYPE": "Attachment Type",
    "NO_ATTACHMENT": "No Attachment",
    "UPLOAD_FILE": "Upload",
    "FILE_UPLOADED": "File Uploaded",
    "ATTACHMENT_PREVIEW": "Attachment Preview",
    "ENTER_ANSWER": "Enter Answer",
    "ANSWER_KEY": "Answer Key",
    "ANSWER_FORMULA_LABEL": "Correct Answer (LaTeX)",
    "ANSWER_PLACEHOLDER": "Example: x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}",

    "CONFIRM_DELETE_SUBMISSIONS_TITLE": "Confirm Deletion of Submissions",
    "CONFIRM_DELETE_SUBMISSIONS_MESSAGE": "This test already has submission data. Saving will delete all existing submissions and grading results. Are you sure?",
    "PROCEED_SAVE": "Delete and Save",

    // 結果ページ
    // /test/[id]/result/page.tsx (等)
    "CANT_OPEN_PAGE": "Cannot open page",
    "FORM_ID": "Form ID:",
    "NOT_GRADED": "Not Graded",
    "POINT_DISPLAY": "Score: {n} pts",
    "TRUE_ANS": "Correct Answer",
    "PREV_PART": "Previous Part",
    "NEXT_PART": "Next Part",
    "SCORE": "Score",
    "POINTS": "pts",

    // 解答ページ
    // /test/[id]/page.tsx
    "NO_TEST_FOUND": "Test not found",
    "SUBMISSION_COMPLETED": "Submission Completed",
    "CHECK_RESULTS": "Check Results >",
    "ERROR": "Error",
    "SENT": "Submitted!",
    "SEND_FAILED": "Submission failed",
    "SEND": "Submit",
    "SENDING": "Submitting...",

    //  /teacher/grading/[testid]/page.tsx
    "PART": "Part",
    "NO_TEST_DATA": "Test data not found.",
    "TOTAL_POINT": "Total Score",
    "UNGRADED_COUNT": "Ungraded",
    "SUCCESS_SAVE_GRADING": "Grading data saved successfully.",
    "ERROR_OCCURRED": "An error occurred.",
    "EXPORT_CSV": "Export CSV",
    "CLASS_ID": "Class ID",
    "TEST_ID": "Test ID",
    "CSV_PART_QNUMBER": "Part-QNumber",
    "CSV_QUESTION": "Question",
    "CSV_ANSWER": "Answer",

    // class
    "EDIT_CLASS": "Edit Class",
    "UPDATE_CLASS": "Update Class",
    "SUCCESS_UPDATE": "Class updated successfully",
    "ADDED_STUDENTS": "Added Students",
    "ADDED_TEACHERS": "Added Teachers",
    "CLASS_INFO": "Class Basic Info",
    "STUDENT_SECTION": "Students",
    "TEACHER_SECTION": "Teachers",
    "SEARCH_PLACEHOLDER_STUDENT": "Search students by name or email",
    "SEARCH_PLACEHOLDER_TEACHER": "Search teachers by name or email",
    "CURRENT_MEMBERS": "Current Members",
    "NO_MEMBERS": "No members added",
    "UPLOAD_ICON": "Select Icon Image",
    "DELETE_ICON": "Delete Icon",
    "COPIED": "Copied to clipboard",
    "INVITATION_QR": "Invitation QR Code",
    "INVITATION_URL": "Invitation URL",
    "COPY_URL": "Copy URL",
    //ClassDetail
    "CLASS_DETAILS": "Class Details",
    "TEST_LIST": "Test List",
    "MEMBERS": "Members",
    "SUBMISSION_STATUS": "Submission Status",
    "NO_TESTS_IN_CLASS": "There are no tests in this class yet",
    "VIEW_DETAILS": "Details",
    "SUBMITTED_STUDENTS": "Submitted Students",
    "UNSUBMITTED_STUDENTS": "Unsubmitted Students",
    "ERROR_INVALID_URL": "Invalid URL",
    "GRADE": "Grade",
    "TAKE_TEST": "Take Test",
    "VIEW_RESULT": "View Results",
    "BEFORE_SUBMISSION_PERIOD": "Before submission period",
    "SUBMISSION_TIME": "Submission Time",
    "DEADLINE": "from deadline",
    "LATE_SUBMISSION": "Submitted late",
    "EARLY_SUBMISSION": "Submitted early",
    "MAX_RESUBMISSIONS": "Maximum resubmissions",
    "REMAINING_RESUBMISSIONS": "Remaining resubmissions",
    "RESUBMIT": "Resubmit",
    "RESUBMIT_W": "Resubmit",

    "CREATE_FOLDER": "Create Folder",
    "NEW_FOLDER_NAME": "Folder Name",
    "DELETE_FOLDER_CONFIRM": "Delete folder? (Items inside will be moved outside)",
    "DROP_HERE": "(Drop here to add)",
    "RENAME_FOLDER": "Rename",
    "DELETE_FOLDER": "Delete",
    "CHANGE_FOLDER_COLOR": "Change Color",
    "SELECT_COLOR": "Select Color",
    "ALLOCATION_POINT": "Points",
    "NAME": "Name",
    "OVERDUE": "Overdue",
    "ON_TIME": "On Time",
    "SUBMIT_PREFIX": "Submitted: ",
    "LATE_PREFIX": "Late by ",
    "LATE_SUFFIX": "",
    "LESS_THAN_A_MINUTE": "Less than a minute",
    "RAW_TEX": "Raw TeX",
    "CLOSE": "Close",
    "ANSWER_LABEL": "Answer",
    "SCORE_LABEL": "Score",
    "MOVE_UP": "Move Up",
    "MOVE_DOWN": "Move Down",
    "DUPLICATE": "Duplicate",
    "AUTO_GRADING": "Auto Grading",
    "AUTO_GRADING_CONFIRM_TITLE": "Execute Auto Grading",
    "AUTO_GRADING_CONFIRM_MESSAGE": "Executing auto grading will overwrite the currently entered scores. Are you sure?",
    "EXECUTE": "Execute",
    "FORMATED_TEX": "Formatted TeX",
    "ITEMS": "Items",
    "SHOW_QUESTION": "Show Question"
};

const dicts = {
    ja: jaDict,
    en: enDict,
};

export const useMsg = () => {
    const { lang } = useContext(LangContext);
    return dicts[lang] || dicts.ja;
};